import { MaterialIcons } from "@expo/vector-icons";
import { useLocalSearchParams, router } from "expo-router";
import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { BottomNav } from "@/components/bottom-nav";
import { BrandHeader } from "@/components/brand-header";

const C = { navy: "#092B4C", teal: "#00A6A6", coral: "#FF625A", gold: "#F4B942", ink: "#102A43", muted: "#6B7C93", line: "#E5ECF2" };
const eventMap: Record<string, any> = { "riyadh-tech": { title: "مؤتمر التقنية والتحول الرقمي", type: "مؤتمر", date: "18 سبتمبر 2026", city: "الرياض", venue: "مركز الملك عبدالله المالي", color: C.teal, attendees: "500+", description: "يستعرض المؤتمر أحدث حلول التقنية والتحول الرقمي، ويجمع قادة الأعمال والمبتكرين وصناع القرار في يوم غني بالجلسات والشراكات." }, "future-mobility": { title: "معرض مستقبل التنقل", type: "معرض", date: "02 أكتوبر 2026", city: "جدة", venue: "جدة سوبر دوم", color: C.coral, attendees: "1.2K", description: "منصة تجمع حلول التنقل الذكي، السيارات الكهربائية، والبنية التحتية المستقبلية في تجربة تفاعلية." }, "design-week": { title: "أسبوع التصميم السعودي", type: "مهرجان", date: "21 أكتوبر 2026", city: "الرياض", venue: "حي جاكس", color: C.gold, attendees: "800+", description: "احتفاء بالمواهب الإبداعية والتصميم المحلي من خلال معارض وورش وتجارب مفتوحة للجمهور." } };
export default function EventDetail() { const { id } = useLocalSearchParams<{ id: string }>(); const event = eventMap[id ?? "riyadh-tech"] ?? eventMap["riyadh-tech"]; const [registered, setRegistered] = useState(false); return <ScreenContainer containerClassName="bg-[#F5F8FB]" className="px-5"><BrandHeader /><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{ paddingBottom: 35 }}><View style={styles.nav}><Pressable onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-forward" size={21} color={C.navy} /></Pressable><Text style={styles.navTitle}>تفاصيل الفعالية</Text><View style={{ width: 40 }} /></View><View style={[styles.cover, { backgroundColor: event.color }]}><View style={styles.coverPattern}><MaterialIcons name="event" size={80} color="#FFFFFF" /></View><View style={styles.coverBadge}><Text style={styles.coverBadgeText}>{event.type}</Text></View></View><Text style={styles.title}>{event.title}</Text><Text style={styles.description}>{event.description}</Text><View style={styles.detailsBox}><Info icon="calendar-today" label="التاريخ" value={event.date} /><Info icon="location-on" label="الموقع" value={`${event.venue} • ${event.city}`} /><Info icon="people-outline" label="المتوقع" value={`${event.attendees} مسجل`} /></View><Text style={styles.section}>البرنامج المختصر</Text><View style={styles.schedule}><Schedule time="09:00" title="التسجيل والاستقبال" color={C.teal} /><Schedule time="10:00" title="الجلسة الافتتاحية" color={C.coral} /><Schedule time="12:30" title="منطقة التجارب والشراكات" color={C.gold} /></View><Pressable onPress={() => setRegistered(!registered)} style={({ pressed }) => [styles.register, registered && styles.registered, pressed && { opacity: 0.8 }]}><MaterialIcons name={registered ? "check-circle" : "how-to-reg"} size={20} color="#FFF" /><Text style={styles.registerText}>{registered ? "تم تسجيلك بنجاح" : "سجّل الآن"}</Text></Pressable>{registered && <View style={styles.success}><MaterialIcons name="qr-code-2" size={25} color={C.teal} /><View style={{ flex: 1 }}><Text style={styles.successTitle}>رمز الدخول جاهز</Text><Text style={styles.successText}>ستجد رمز QR الخاص بك في تذاكرك.</Text></View></View>}</ScrollView><BottomNav /></ScreenContainer>; }
function Info({ icon, label, value }: { icon: any; label: string; value: string }) { return <View style={styles.info}><View style={styles.infoIcon}><MaterialIcons name={icon} size={19} color={C.teal} /></View><View style={{ flex: 1 }}><Text style={styles.infoLabel}>{label}</Text><Text style={styles.infoValue}>{value}</Text></View></View>; }
function Schedule({ time, title, color }: { time: string; title: string; color: string }) { return <View style={styles.scheduleRow}><View style={[styles.scheduleDot, { backgroundColor: color }]} /><Text style={styles.scheduleTime}>{time}</Text><Text style={styles.scheduleTitle}>{title}</Text></View>; }
const styles = StyleSheet.create({ nav: { flexDirection: "row-reverse", alignItems: "center", justifyContent: "space-between", paddingTop: 6, paddingBottom: 16 }, back: { width: 40, height: 40, borderRadius: 13, backgroundColor: "#FFF", alignItems: "center", justifyContent: "center" }, navTitle: { color: C.ink, fontSize: 15, fontWeight: "800" }, cover: { height: 170, borderRadius: 23, overflow: "hidden", alignItems: "center", justifyContent: "center", position: "relative" }, coverPattern: { width: 125, height: 125, borderRadius: 70, backgroundColor: "#FFFFFF25", alignItems: "center", justifyContent: "center" }, coverBadge: { position: "absolute", top: 13, right: 13, backgroundColor: "#FFFFFF35", paddingHorizontal: 10, paddingVertical: 6, borderRadius: 8 }, coverBadgeText: { color: "#FFF", fontSize: 10, fontWeight: "800" }, title: { color: C.ink, fontSize: 24, fontWeight: "800", textAlign: "right", marginTop: 18 }, description: { color: C.muted, fontSize: 12, lineHeight: 20, textAlign: "right", marginTop: 8 }, detailsBox: { backgroundColor: "#FFF", borderRadius: 18, padding: 12, marginTop: 17, gap: 12 }, info: { flexDirection: "row-reverse", alignItems: "center", gap: 10 }, infoIcon: { width: 35, height: 35, borderRadius: 11, backgroundColor: "#E4F8F5", alignItems: "center", justifyContent: "center" }, infoLabel: { color: C.muted, fontSize: 9, textAlign: "right" }, infoValue: { color: C.ink, fontSize: 11, fontWeight: "700", textAlign: "right", marginTop: 2 }, section: { color: C.ink, fontSize: 17, fontWeight: "800", textAlign: "right", marginTop: 24, marginBottom: 10 }, schedule: { backgroundColor: "#FFF", borderRadius: 17, padding: 14 }, scheduleRow: { flexDirection: "row-reverse", alignItems: "center", gap: 9, paddingVertical: 8 }, scheduleDot: { width: 9, height: 9, borderRadius: 5 }, scheduleTime: { color: C.muted, fontSize: 10, width: 40, textAlign: "right" }, scheduleTitle: { color: C.ink, fontSize: 12, fontWeight: "700", flex: 1, textAlign: "right" }, register: { backgroundColor: C.teal, borderRadius: 14, height: 52, flexDirection: "row-reverse", alignItems: "center", justifyContent: "center", gap: 8, marginTop: 20 }, registered: { backgroundColor: C.navy }, registerText: { color: "#FFF", fontSize: 14, fontWeight: "800" }, success: { backgroundColor: "#E9FAF8", borderRadius: 15, padding: 13, flexDirection: "row-reverse", alignItems: "center", gap: 10, marginTop: 12 }, successTitle: { color: C.navy, fontSize: 12, fontWeight: "800", textAlign: "right" }, successText: { color: C.muted, fontSize: 10, marginTop: 3, textAlign: "right" },
});
