import { MaterialIcons } from "@expo/vector-icons";
import { router } from "expo-router";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { BrandHeader } from "@/components/brand-header";
import { BottomNav } from "@/components/bottom-nav";

const C = { navy: "#092B4C", teal: "#00A6A6", coral: "#FF625A", gold: "#F4B942", ink: "#102A43", muted: "#6B7C93" };
const roles = [
  { id: "owner", title: "الجهة المالكة", subtitle: "أنشئ فعاليتك وتابع كل التفاصيل", icon: "business-center" as const, color: C.navy, route: "/(tabs)" },
  { id: "operator", title: "الشركة المنفذة", subtitle: "استلم المهام وارفع حالة الإنجاز", icon: "engineering" as const, color: C.teal, route: "/roles/operator" },
  { id: "exhibitor", title: "العارضون", subtitle: "احجز مساحة البوث وأدر تجهيزاتك", icon: "storefront" as const, color: C.coral, route: "/roles/exhibitor" },
  { id: "attendee", title: "الحضور", subtitle: "اكتشف الفعاليات وسجّل حضورك", icon: "confirmation-number" as const, color: "#5674D8", route: "/roles/attendee" },
  { id: "visitor", title: "مطلع على الفعاليات", subtitle: "تصفح تقويم الفعاليات السنوي", icon: "explore" as const, color: C.gold, route: "/(tabs)/explore" },
];
export default function RoleSelection() { return <ScreenContainer containerClassName="bg-[#F5F8FB]" className="px-5"><BrandHeader /><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{ paddingBottom: 36 }}><View style={styles.hero}><Text style={styles.eyebrow}>منصة واحدة، أربع تجارب</Text><Text style={styles.title}>كيف تريد استخدام{`\n`}eventz اليوم؟</Text><Text style={styles.body}>اختر دورك لتجربة الواجهة المناسبة لك، ويمكنك تغيير الاختيار لاحقًا.</Text></View><Text style={styles.section}>اختر الواجهة</Text><View style={styles.grid}>{roles.map((role) => <Pressable key={role.id} onPress={() => router.replace(role.route as any)} style={({ pressed }) => [styles.card, pressed && styles.pressed, { borderTopColor: role.color }]}><View style={[styles.icon, { backgroundColor: `${role.color}16` }]}><MaterialIcons name={role.icon} size={25} color={role.color} /></View><Text style={styles.cardTitle}>{role.title}</Text><Text style={styles.cardBody}>{role.subtitle}</Text><View style={styles.cardAction}><Text style={{ color: role.color, fontSize: 11, fontWeight: "800" }}>الدخول للواجهة</Text><MaterialIcons name="arrow-back" size={16} color={role.color} /></View></Pressable>)}</View><View style={styles.note}><MaterialIcons name="swap-vert" size={23} color={C.teal} /><Text style={styles.noteText}>يمكن لكل جهة استخدام eventz بصلاحيات وبيانات مختلفة تناسب دورها في الفعالية.</Text></View></ScrollView><BottomNav /></ScreenContainer>; }
const styles = StyleSheet.create({ header: { flexDirection: "row-reverse", alignItems: "center", gap: 9, paddingTop: 8 }, mark: { width: 31, height: 31, position: "relative" }, dot: { position: "absolute", width: 11, height: 11, borderRadius: 6 }, logo: { color: C.navy, fontSize: 23, fontWeight: "800", letterSpacing: -1 }, hero: { backgroundColor: C.navy, borderRadius: 24, padding: 22, marginTop: 27 }, eyebrow: { color: "#7DE3DB", fontSize: 12, fontWeight: "800", textAlign: "right" }, title: { color: "#FFF", fontSize: 27, fontWeight: "800", lineHeight: 36, textAlign: "right", marginTop: 9 }, body: { color: "#C2D2E1", fontSize: 12, lineHeight: 19, textAlign: "right", marginTop: 10 }, section: { color: C.ink, fontSize: 17, fontWeight: "800", textAlign: "right", marginTop: 25, marginBottom: 12 }, grid: { flexDirection: "row-reverse", flexWrap: "wrap", gap: 11 }, card: { width: "48.3%", backgroundColor: "#FFF", borderRadius: 17, borderTopWidth: 4, padding: 14, minHeight: 169, shadowColor: "#0A2342", shadowOpacity: 0.04, shadowRadius: 8, elevation: 1 }, icon: { width: 43, height: 43, borderRadius: 13, alignItems: "center", justifyContent: "center", alignSelf: "flex-end" }, cardTitle: { color: C.ink, fontSize: 12, lineHeight: 18, fontWeight: "800", textAlign: "right", marginTop: 11 }, cardBody: { color: C.muted, fontSize: 10, lineHeight: 16, textAlign: "right", marginTop: 4 }, cardAction: { flexDirection: "row-reverse", alignItems: "center", gap: 5, marginTop: 13, justifyContent: "flex-start" }, pressed: { opacity: 0.78, transform: [{ scale: 0.985 }] }, note: { backgroundColor: "#E9FAF8", borderRadius: 15, padding: 13, flexDirection: "row-reverse", alignItems: "center", gap: 10, marginTop: 18 }, noteText: { color: C.muted, fontSize: 10, lineHeight: 17, flex: 1, textAlign: "right" }, });
