import { MaterialIcons } from "@expo/vector-icons";
import { router } from "expo-router";
import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { BrandHeader } from "@/components/brand-header";

const C = { navy: "#092B4C", teal: "#00A6A6", ink: "#102A43", muted: "#6B7C93", line: "#E5ECF2" };
const roles = [
  { id: "owner", label: "الجهة المالكة", icon: "business-center" as const, color: C.navy, route: "/(tabs)" },
  { id: "operator", label: "الشركة المنفذة", icon: "engineering" as const, color: C.teal, route: "/roles/operator" },
  { id: "exhibitor", label: "العارضون", icon: "storefront" as const, color: "#FF625A", route: "/roles/exhibitor" },
  { id: "attendee", label: "الحضور", icon: "person-outline" as const, color: "#5674D8", route: "/roles/attendee" },
  { id: "visitor", label: "مطلع على الفعاليات", icon: "explore" as const, color: "#C58B00", route: "/(tabs)/explore" },
];
export default function ProfileScreen() {
  const [role, setRole] = useState("owner");
  return <ScreenContainer containerClassName="bg-[#F5F8FB]" className="px-5"><BrandHeader /><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{ paddingBottom: 40 }}><View style={styles.top}><View><Text style={styles.kicker}>حسابك في eventz</Text><Text style={styles.title}>مرحباً، انس</Text></View><View style={styles.avatar}><Text style={styles.avatarText}>أ</Text></View></View><View style={styles.profileCard}><View style={styles.profileAvatar}><Text style={styles.profileAvatarText}>أ</Text></View><View style={{ flex: 1 }}><Text style={styles.name}>انس</Text><Text style={styles.email}>مدير فعاليات • السعودية</Text></View><Pressable><MaterialIcons name="edit" size={20} color={C.teal} /></Pressable></View><Text style={styles.section}>جرّب المنصة من منظور مختلف</Text><Text style={styles.helper}>هذا النموذج يوضح كيف يخدم eventz كل طرف في منظومة الفعالية.</Text><View style={styles.roles}>{roles.map((item) => <Pressable key={item.id} onPress={() => { setRole(item.id); router.replace(item.route as any); }} style={[styles.role, role === item.id && { borderColor: item.color, backgroundColor: `${item.color}08` }]}><View style={[styles.roleIcon, { backgroundColor: `${item.color}16` }]}><MaterialIcons name={item.icon} size={22} color={item.color} /></View><Text style={[styles.roleText, role === item.id && { color: item.color }]}>{item.label}</Text>{role === item.id && <MaterialIcons name="check-circle" size={18} color={item.color} style={{ marginRight: "auto" }} />}</Pressable>)}</View><View style={styles.info}><MaterialIcons name="lightbulb-outline" size={22} color={C.teal} /><View style={{ flex: 1 }}><Text style={styles.infoTitle}>النموذج الأولي</Text><Text style={styles.infoText}>يمكنك التنقل بين الشاشات من شريط التبويب السفلي وتجربة المسارات الأساسية.</Text></View></View><View style={styles.menu}><MenuRow icon="settings" label="الإعدادات" /><MenuRow icon="help-outline" label="المساعدة والتواصل" /><MenuRow icon="language" label="العربية  •  English" /></View></ScrollView></ScreenContainer>;
}
function MenuRow({ icon, label }: { icon: any; label: string }) { return <Pressable style={({ pressed }) => [styles.menuRow, pressed && { opacity: 0.65 }]}><View style={styles.menuIcon}><MaterialIcons name={icon} size={19} color={C.muted} /></View><Text style={styles.menuText}>{label}</Text><MaterialIcons name="chevron-left" size={20} color="#A0ADBA" style={{ marginRight: "auto" }} /></Pressable>; }
const styles = StyleSheet.create({ top: { flexDirection: "row-reverse", alignItems: "center", justifyContent: "space-between", paddingTop: 8 }, kicker: { color: C.teal, fontSize: 12, fontWeight: "700", textAlign: "right" }, title: { color: C.navy, fontSize: 26, fontWeight: "800", marginTop: 5, textAlign: "right" }, avatar: { width: 45, height: 45, backgroundColor: C.navy, borderRadius: 15, alignItems: "center", justifyContent: "center" }, avatarText: { color: "#FFF", fontSize: 19, fontWeight: "800" }, profileCard: { backgroundColor: "#FFF", borderRadius: 19, padding: 15, flexDirection: "row-reverse", alignItems: "center", gap: 11, marginTop: 20 }, profileAvatar: { width: 50, height: 50, borderRadius: 16, backgroundColor: "#E4F8F5", alignItems: "center", justifyContent: "center" }, profileAvatarText: { color: C.teal, fontSize: 21, fontWeight: "800" }, name: { color: C.ink, fontSize: 15, fontWeight: "800", textAlign: "right" }, email: { color: C.muted, fontSize: 10, textAlign: "right", marginTop: 4 }, section: { color: C.ink, fontSize: 17, fontWeight: "800", textAlign: "right", marginTop: 26 }, helper: { color: C.muted, fontSize: 11, lineHeight: 18, textAlign: "right", marginTop: 6 }, roles: { gap: 9, marginTop: 15 }, role: { backgroundColor: "#FFF", borderRadius: 15, padding: 11, flexDirection: "row-reverse", alignItems: "center", gap: 10, borderWidth: 1.5, borderColor: "transparent" }, roleIcon: { width: 39, height: 39, borderRadius: 12, alignItems: "center", justifyContent: "center" }, roleText: { color: C.ink, fontSize: 12, fontWeight: "800", textAlign: "right" }, info: { backgroundColor: "#E9FAF8", borderRadius: 15, padding: 13, flexDirection: "row-reverse", gap: 10, marginTop: 21 }, infoTitle: { color: C.navy, fontSize: 12, fontWeight: "800", textAlign: "right" }, infoText: { color: C.muted, fontSize: 10, lineHeight: 16, textAlign: "right", marginTop: 4 }, menu: { backgroundColor: "#FFF", borderRadius: 16, paddingHorizontal: 13, marginTop: 14 }, menuRow: { flexDirection: "row-reverse", alignItems: "center", paddingVertical: 14, gap: 10, borderBottomWidth: 1, borderBottomColor: C.line }, menuIcon: { width: 31, height: 31, borderRadius: 10, backgroundColor: "#F5F8FB", alignItems: "center", justifyContent: "center" }, menuText: { color: C.ink, fontSize: 12, fontWeight: "700" },
});
